### ISSUE TITLE
Migrate from libgnome-keyring to libsecret

### ISSUE THREAD

**Issue by openarun** [linuxdeepin/dpa-ext-gnomekeyring#1]
As libgnome-keyring is depreciated and has been superseded by libsecret

https://wiki.gnome.org/Initiatives/GnomeGoals/LibsecretMigration

**Comment by openarun** [comment]
@xmuli Any update on this?

**Comment by XMuli** [comment]
@justforlxz  你看下？

**Comment by ClayStan** [comment]
Migrate from libgnome-keyring to libsecret : https://github.com/linuxdeepin/dpa-ext-gnomekeyring/commit/157fc217ec6e45f265999db301778c9ae95ac48e

**Comment by ppphp** [comment]
> Migrate from libgnome-keyring to libsecret : [157fc21](https://github.com/linuxdeepin/dpa-ext-gnomekeyring/commit/157fc217ec6e45f265999db301778c9ae95ac48e)

When will you make a release for the change? Thank you.
